### PR TITLE
New Learning Hour - Teach Back 

### PR DESCRIPTION
**Pull request by peitor**

### CODE REVIEW

**Comment by emilybache** [comment]
Thanks for the contribution. Do you want my help with getting this onto the website? Or perhaps someone else from the society is helping you already?

**Comment by emilybache** [comment]
I'm really happy to see this, thankyou Peter. I tweaked a few things and made some suggestions in the pull request. Perhaps we could schedule a call sometime next week and talk about this?

**Comment by peitor** [comment]
> I tweaked a few things and made some suggestions in the pull request. 

Looks good to me.



> Perhaps we could schedule a call sometime next week and talk about this?

Yes, we can. I send you an email with availabilities. Lets continue there.


THANK YOU!

**Comment by peitor** [comment]
Hi Emily
As per our conversation, I updated the PR with the 4 changes.
I also improved my company name.

THANK YOU!

**Comment by emilybache** [comment]
Happy to have your contribution on the site, Peter!

**Pull request merged**
